# https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: npm
    # React client
    directory: /frontend
    schedule:
      interval: "daily"
    # Open PR limit only affects non-security updates
    open-pull-requests-limit: 0
    labels:
      - "Front end"
      - "Security"
  - package-ecosystem: gradle
    # Java API
    directory: /backend
    schedule:
      interval: "daily"
    labels:
      - "Backend"
      - "DevOps"
      - "Security"
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "DevOps"
      - "Security"
# This is possible, but doesn't seem actually all that useful
# - package-ecosystem: terraform
#   directory: /ops
#   schedule:
#     interval: "daily"
