# configuration for dev and demo non-default users with no Okta entity management
simple-report-initialization:
  user-roles-map:
    ? username: ben@sample.com
      first-name: Ben
      middle-name: Billy
      last-name: Barnes
      suffix: III
    : - USER
    ? username: jamar@sample.com
      first-name: Jamar
      middle-name: Donald
      last-name: Jackson
    : - USER
      - ENTRY_ONLY
    ? username: sarah@sample.com
      first-name: Sarah
      middle-name: Sally
      last-name: Samuels
    : - USER
      - ADMIN
