spring:
  config:
    use-legacy-processing: true
  main:
    banner-mode: "OFF"
  datasource:
    username: simple_report_app
    password: api123
    url: jdbc:postgresql://localhost:${SR_DB_PORT:5432}/simple_report
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: validate
    open-in-view: false # this is misleading: we actually have a filter that does this instead
    properties:
      hibernate:
        default_schema: public # Using the public schema for now, so we don't have to add a manual step to the deploy process
  liquibase:
    default-schema: ${spring.jpa.properties.hibernate.default_schema}
graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    exception-handlers-enabled: true
  tools:
    schema-location-pattern: "**/*.graphqls"
  datetime:
    scalars:
      Date:
        scalar-name: DateTime
        format: yyyy-MM-dd'T'HH:MM:ss'Z'
      LocalDate:
        format: yyyy-MM-dd
okta:
  oauth2:
    issuer: https://hhs-prime.okta.com/oauth2/default
    client-id: ${OKTA_OAUTH2_CLIENT_ID}
    client-secret: ${OKTA_OAUTH2_CLIENT_SECRET:MISSING}
    groups-claim: ${simple-report.authorization.role-claim}
  client:
    org-url: https://hhs-prime.okta.com
    token: ${OKTA_API_KEY:MISSING}
simple-report:
  data-hub:
    # these are overridden by application-dev, -prod, -test, etc
    upload-enabled: false
    upload-url: ""
    max-csv-rows: 999
    api-key: ${DATAHUB_API_KEY:MISSING}
    secret-slack-notify-webhook-url: ${SECRET_SLACK_NOTIFY_WEBHOOK_URL:MISSING}
    upload-schedule: "0 0 11 * * *" # Daily at 11:00 AM Eastern Time
    upload-timezone: America/New_York
  authorization:    
    # these are overridden by application-dev, -prod, -test, etc
    role-claim: dev_roles
    role-prefix: "SR-DEV-TENANT:"
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} [Query: %X{graphql-query}] %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
