spring:
  profiles.include: okta-dev, auth-dev
  jpa:
    properties:
      hibernate:
        default_schema: simple_report
graphql.servlet.cors:
  allowed-origins:
    - http://localhost:3000
    - https://simple-report-qa.app.cloud.gov
    - https://simple-report-sandbox.app.cloud.gov
simple-report:
  site-admin-emails:
    - bwarfield@cdc.gov
    - tim.best@usds.dhs.gov
    - qom2@cdc.gov # a.k.a. abeckett@cdc.gov
    - jonathan.eskew@cms.hhs.gov
    - neil.s.sharma@omb.eop.gov
    - wsullivan@cdc.gov
    - jeremy.a.zitomer@omb.eop.gov
    - nicholas.scialli@usds.dhs.gov
    - qrk8@cdc.gov # Sparkle
    - David.w.methvin@omb.eop.gov
    - thomas.a.nielsen@omb.eop.gov
