spring:
  autoconfigure:
    exclude: # avoid running OAuth2 autoconfigure, even though we are setting some OAuth2 properties by default
      - com.okta.spring.boot.oauth.OktaOAuth2AutoConfig
      - com.okta.spring.boot.oauth.OktaOAuth2ResourceServerAutoConfig
      - org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration
simple-report:
  admin-emails:
    - ruby@example.com
  demo-users:
    default-user:
      identity:
        username: bob@bobby.bob
        first-name: Bob
        last-name: Bobberoo
      authorization:
        organization-external-id: ${SR_DEMO_USER_ORG:DIS_ORG}
        granted-roles: ${SR_DEMO_USER_ROLE:ADMIN}
