spring:
  profiles.include: no-security,local
  liquibase:
    user: simple_report_migrations
    password: migrations456
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: false # override this in application-local.yaml to get pretty-printed SQL all the time
        default_schema: simple_report
logging:
  level:
    # NOTE: add any of the below in application-local.yaml to turn on something interesting
    # Hibernate SQL query logging: basically the same as show_sql, above, but through slf4j
    # org.hibernate.SQL: DEBUG
    # Hibernate input and output value logging: SUPER VERBOSE
    # org.hibernate.type: TRACE
    # Always have our own debug logging turned on in dev environments:
    gov.cdc.usds: DEBUG
simple-report-initialization:
  organization:
    facility-name: Dis Organization
    external-id: DIS_ORG
    clia-number: "000111222-3"
  provider:
    first-name: Fred
    last-name: Flintstone
    provider-id: PEBBLES
    telephone: (202) 555-1212
    address:
      street-1: 123 Main Street
      city: Oz
      state: KS
      zip-code: "12345"
  configured-device-types:
    - LumiraDX
    - Quidel Sofia 2
