spring:
  profiles.include: okta-dev, auth-dev
graphql.servlet.cors:
  allowed-origins:
    - https://simplereportdevapp.z13.web.core.windows.net
    - https://simple-report-api-dev.azurewebsites.net
    - https://simple-report-api-demo.azurewebsites.net
    - https://simple-report-api-test.azurewebsites.net
    - https://simple-report-demo.azureedge.net
    - https://simple-report-dev.azureedge.net
    - https://simple-report-test.azureedge.net
    - https://dev.simplereport.gov
    - https://demo.simplereport.gov
    - https://test.simplereport.gov
