# Bean profile to be included in deployment-specific profiles
# for TEST deployments.
okta:
  oauth2:
    client-id: 0oa6na9px2vFmPLam4h6
simple-report:
  authorization:
    role-claim: pentest_roles
    role-prefix: "SR-PENTEST-TENANT:"