spring:
  profiles.include: no-security, single-tenant, no-okta-mgmt, create-sample-data
graphql.servlet.cors:
  allowed-origins:
    - https://simple-report-api-demo.azurewebsites.net
    - https://simple-report-demo.azureedge.net
    - https://demo.simplereport.gov
simple-report:
  feature-flags:
    patient-experience: true