graphql.servlet.cors:
  allowed-origins:
    - https://simplereport.cdc.gov
    - https://simple-report-api-prod.azurewebsites.net
    - https://simple-report-prod.azureedge.net
    - https://prod.simplereport.gov
    - https://simplereport.gov
simple-report:
  data-hub:
    uploadurl: "https://prime-data-hub-prod.azurefd.net/api/reports"