spring:
  profiles.include: no-security, no-okta-mgmt, create-sample-data
graphql.servlet.cors:
  allowed-origins:
    - https://simple-report-api-demo.azurewebsites.net
    - https://simple-report-demo.azureedge.net
    - https://demo.simplereport.gov
simple-report:
  patient-link-url: https://demo.simplereport.gov/app/pxp?plid=
  sendgrid:
    enabled: false
    from-email: support@simplereport.gov
    account-request-recipient: support@simplereport.gov
twilio:
  enabled: false
