spring:
  profiles.include: no-security, no-okta-mgmt, create-sample-data
graphql.servlet.cors:
  allowed-origins:
    - https://simple-report-api-training.azurewebsites.net
    - https://simple-report-training.azureedge.net
    - https://training.simplereport.gov
simple-report:
  patient-link-url: https://training.simplereport.gov/app/pxp?plid=
  feature-flags:
    patient-links: true
    account-request: true
  sendgrid:
    enabled: false
twilio:
  enabled: false
