spring:
  autoconfigure:
    exclude: # avoid running OAuth2 autoconfigure, even though we are setting some OAuth2 properties by default
      - com.okta.spring.boot.oauth.OktaOAuth2AutoConfig
      - com.okta.spring.boot.oauth.OktaOAuth2ResourceServerAutoConfig
      - org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration
simple-report-initialization.default-user:
  username: bob@example.com
  first-name: Bobbity
  middle-name: Bob
  last-name: Bobberoo
simple-report:
  admin-emails:
    - bob@example.com