spring:
  profiles.include: no-security, single-tenant, no-okta-mgmt, create-sample-data
graphql.servlet.cors:
  allowed-origins:
    - https://simple-report-api-demo.azurewebsites.net
    - https://simple-report-demo.azureedge.net
    - https://demo.simplereport.gov
simple-report:
  patient-link-url: https://demo.simplereport.gov/app/pxp?plid=
  feature-flags:
    patient-links: true
twilio:
  enabled: true
  from-number: "+14045312484"
