spring:
  main:
    banner-mode: "OFF"
  datasource:
    username: simple_report_app
    password: api123
    url: jdbc:postgresql://localhost:${SR_DB_PORT:5432}/simple_report
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        default_schema: public # Using the public schema for now, so we don't have to add a manual step to the deploy process
  liquibase:
    default-schema: ${spring.jpa.properties.hibernate.default_schema}
graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
  tools:
    schema-location-pattern: "**/*.graphqls"
  datetime:
    scalars:
      Date:
        scalar-name: DateTime
        format: yyyy-MM-dd'T'HH:MM:ss'Z'
      LocalDate:
        format: yyyy-MM-dd
okta:
  oauth2:
    issuer: https://hhs-prime.okta.com/oauth2/default
    # DEPRECATION: the FAKE fallback here is to enable behavior that
    # we would be better off not enabling. Removal planned before 1/15/2021
    client-id: ${clientID:FAKE}
    client-secret: ${OKTA_OAUTH2_CLIENT_ID:FAKE}
    groups-claim: ${simple-report.authorization.role-claim}
simple-report-initialization:
  device-types:
    - name: Abbott IDNow
      manufacturer: Abbott
      model: ID Now
      loinc-code: "94534-5"
    - name: Abbott BinaxNow
      manufacturer: Abbott
      model: BinaxNOW COVID-19 Ag Card
      loinc-code: "94558-4"
    - name: Quidel Sofia 2
      manufacturer: Quidel
      model: Sofia 2 SARS Antigen FIA
      loinc-code: "95209-3"
    - name: BD Veritor
      manufacturer: Becton, Dickinson and Company (BD)
      model: "BD Veritor System for Rapid Detection of SARS-CoV-2*"
      loinc-code: "94558-4"
    - name: LumiraDX
      manufacturer: LumiraDx UK Ltd.
      model: LumiraDx SARS-CoV-2 Ag Test*
      loinc-code: "95209-3"
simple-report:
  data-hub:
    # these are overridden by application-dev, -prod, -test, etc
    upload-enabled: false
    upload-url: ""
    max-csv-rows: 999
    api-key: ${DATAHUB_API_KEY:MISSING}
    secret-slack-notify-webhook-url: ${SECRET_SLACK_NOTIFY_WEBHOOK_URL:MISSING}
  authorization:
    role-claim: prod_roles
    role-prefix: "SR-PROD-TENANT:"
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} [Query: %X{graphql-query}] %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
