spring:
  profiles.include: okta-test, server-debug, local
  liquibase:
    user: simple_report_migrations
    password: migrations456
  jpa:
    properties:
      hibernate:
        show_sql: true
        default_schema: simple_report
logging:
  level:
    # NOTE: look in application-dev.yaml for other things that might be worth turning on
    gov.cdc.usds: DEBUG
