spring:
  profiles.include: okta-pentest
graphql.servlet.cors:
  allowed-origins:
    - https://simple-report-api-pentest.azurewebsites.net
    - https://simple-report-pentest.azureedge.net
    - https://pentest.simplereport.gov
simple-report:
  site-admin-emails:
    - bwarfield@cdc.gov
    - tim.best@usds.dhs.gov
    - qom2@cdc.gov # a.k.a. abeckett@cdc.gov
    - jonathan.eskew@cms.hhs.gov
    - neil.s.sharma@omb.eop.gov
    - wsullivan@cdc.gov
    - jeremy.a.zitomer@omb.eop.gov
    - nicholas.scialli@usds.dhs.gov
    - qrk8@cdc.gov # Sparkle
    - thomas.a.nielsen@omb.eop.gov
    - adam@skylight.digital
    - josh@skylight.digital
    - qyl5@cdc.gov # Brett
  patient-link-url: https://pentest.simplereport.gov/app/pxp?plid=
  feature-flags:
    patient-links: true
    account-request: true
  sendgrid:
    enabled: true
twilio:
  enabled: true
