# configuration for dev and demo non-default users with no Okta entity management
simple-report.demo-users:
  alternate-users:
    - identity:
        username: ben@sample.com
        first-name: Ben
        middle-name: Billy
        last-name: Barnes
        suffix: III
      authorization:
        organization-external-id: DIS_ORG
        granted-roles: 
          - USER
    - identity:
        username: jamar@sample.com
        first-name: Jamar
        middle-name: Donald
        last-name: Jackson
      authorization:
        organization-external-id: DIS_ORG
        granted-roles: 
          - USER
          - ENTRY_ONLY
    - identity:
        username: sarah@sample.com
        first-name: Sarah
        middle-name: Sally
        last-name: Samuels
      authorization:
        organization-external-id: DIS_ORG
        granted-roles: 
          - USER
          - ADMIN
