spring:
  profiles.include: okta-pentest
simple-report:
  patient-link-url: https://pentest.simplereport.gov/app/pxp?plid=
  sendgrid:
    enabled: true
  cors:
    allowed-origins:
      - https://simple-report-api-pentest.azurewebsites.net
      - https://simple-report-pentest.azureedge.net
      - https://pentest.simplereport.gov
twilio:
  enabled: true
