spring:
  profiles.include: no-security, single-tenant, no-okta-mgmt, create-sample-data
graphql.servlet.cors:
  allowed-origins:
    - https://simple-report-api-training.azurewebsites.net
    - https://simple-report-training.azureedge.net
    - https://training.simplereport.gov
