# configuration for dev and demo non-default users with no Okta entity management
simple-report.demo-users:
  alternate-users:
    - identity:
        username: ben@sample.com
        first-name: Ben
        middle-name: Billy
        last-name: Barnes
        suffix: III
      roles:
        - USER
    - identity:
        username: jamar@sample.com
        first-name: Jamar
        middle-name: Donald
        last-name: Jackson
      roles:
        - USER
        - ENTRY_ONLY
    - identity:
        username: sarah@sample.com
        first-name: Sarah
        middle-name: Sally
        last-name: Samuels
      roles:
        - USER
        - ADMIN
