spring:
  profiles.include: okta-dev, auth-dev
graphql.servlet.cors:
  allowed-origins:
    - https://simplereportdevapp.z13.web.core.windows.net
    - https://simple-report-api-dev.azurewebsites.net
    - https://simple-report-dev.azureedge.net
    - https://dev.simplereport.gov
simple-report:
  admin-emails:
    - bwarfield@cdc.gov
    - tim.best@usds.dhs.gov
    - qom2@cdc.gov # a.k.a. abeckett@cdc.gov
    - jonathan.eskew@cms.hhs.gov
    - neil.s.sharma@omb.eop.gov
    - wsullivan@cdc.gov
    - jeremy.a.zitomer@omb.eop.gov
    - eapau@cdc.gov
    - qrk8@cdc.gov # Sparkle
    - David.w.methvin@omb.eop.gov
    - thomas.a.nielsen@omb.eop.gov
  data-hub:
      upload-enabled: true
      upload-url: "https://prime-data-hub-test.azurefd.net/api/reports?option=SkipInvalidItems"
