spring:
  profiles.include: okta-dev, server-debug
cors:
  allowed-origins:
    - https://simplereportdevapp.z13.web.core.windows.net
    - https://simple-report-api-dev.azurewebsites.net
    - https://simple-report-dev.azureedge.net
    - https://dev.simplereport.gov
simple-report:
  data-hub:
    upload-enabled: false
    upload-url: "https://prime-data-hub-test.azurefd.net/api/reports?option=SkipInvalidItems"
    upload-schedule: "0 0/15 * * * *" # every 15min on the clock 1:00, 1:15, 1:30, etc
    max-csv-rows: 25
  patient-link-url: https://dev.simplereport.gov/app/pxp?plid=
  sendgrid:
    enabled: false
twilio:
  enabled: true
