spring:
  # create-sample-data is currently subtly supporting single-tenant, because single-tenant assumes
  # that simple-report-initialization.organization.external-id is set
  profiles.include: no-security, single-tenant, create-sample-data
graphql.servlet.cors:
  allowed-origins:
    - https://simple-report-api-demo.azurewebsites.net
    - https://simple-report-demo.azureedge.net
    - https://demo.simplereport.gov
