spring:
  profiles.include: okta-dev, server-debug
graphql.servlet.cors:
  allowed-origins:
    - https://simplereportdevapp.z13.web.core.windows.net
    - https://simple-report-api-dev.azurewebsites.net
    - https://simple-report-dev.azureedge.net
    - https://dev.simplereport.gov
simple-report:
  site-admin-emails:
    - bwarfield@cdc.gov
    - tim.best@usds.dhs.gov
    - qom2@cdc.gov # a.k.a. abeckett@cdc.gov
    - jonathan.eskew@cms.hhs.gov
    - neil.s.sharma@omb.eop.gov
    - wsullivan@cdc.gov
    - jeremy.a.zitomer@omb.eop.gov
    - nicholas.scialli@usds.dhs.gov
    - qrk8@cdc.gov # Sparkle
    - David.w.methvin@omb.eop.gov
    - thomas.a.nielsen@omb.eop.gov
    - adam@skylight.digital
    - josh@skylight.digital
    - qom5@cdc.gov # Heather
    - qpu1@cdc.gov # Katherine
  data-hub:
    upload-enabled: false
    upload-url: "https://prime-data-hub-test.azurefd.net/api/reports?option=SkipInvalidItems"
    upload-schedule: "0 0/15 * * * *" # every 15min on the clock 1:00, 1:15, 1:30, etc
    max-csv-rows: 25
  patient-link-url: https://dev.simplereport.gov/app/pxp?plid=
  feature-flags:
    patient-links: true
twilio:
  enabled: true