graphql.servlet.cors:
  allowed-origins:
    - https://simplereport.cdc.gov
simple-report:
  data-hub:
    upload-enabled: true
    upload-url: "https://prime-data-hub-prod.azurefd.net/api/reports"
    max-csv-rows: 999
    api-key: ${DATAHUB_API_KEY:MISSING}
    secret-slack-notify-webhook-url: ${SECRET_SLACK_NOTIFY_WEBHOOK_URL:MISSING}
