graphql.servlet.cors:
  allowed-origins:
    - https://simplereport.cdc.gov
simple-report:
  data-hub:
    upload-enabled: true
    upload-url: "https://prime-data-hub-prod.azurefd.net/api/reports"
    max-csv-rows: 999
    api-key: ${datahubApiKey:MISSING_PROD_DATAHUB_KEY}
    secret-slack-notify-webhook-url: ${secretSlackNotifyWebhookUrl:MISSING_PROD_SLACK_WEBHOOK_URL}
