simple-report-initialization.default-user:
  username: bob@example.com
  first-name: Bobbity
  middle-name: Bob
  last-name: Bobberoo
simple-report-initialization.admin-user:
  username: ruby@example.com
  first-name: Ruby
  middle-name: Raven
  last-name: Reynolds
simple-report:
  admin-emails:
    - ruby@example.com