name: Chromatic

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - "frontend/src/**"

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Chromatic wants the history
      - name: Install dependencies
        run: yarn
        working-directory: ./frontend
      - name: Publish to Chromatic
        if: github.ref != 'refs/heads/main'
        uses: chromaui/action@v1
        with:
          workingDir: ./frontend  # This parameter is undocumented
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          ignoreLastBuildOnBranch: "**"  # Better comparisons after rebasing
      - name: Publish to Chromatic (auto-accept changes on merge main)
        if: github.ref == 'refs/heads/main'
        uses: chromaui/action@v1
        with:
          workingDir: ./frontend
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          ignoreLastBuildOnBranch: "**"
          autoAcceptChanges: true  # handle squash-on-merge
