name: Deploy Azure Resources

on: push

defaults:
  run:
    working-directory: ./backend

jobs:
  build-image:
    runs-on: ubuntu-latest
    if: contains('
      refs/heads/ci_cd
      ', github.ref)
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: install AZ
        run: sudo apt-get install azure-cli
      - name: Build and push Docker images
        env:
          ARM_CLIENT_ID: ${{ secrets.TERRAFORM_ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.TERRAFORM_ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.TERRAFORM_ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.TERRAFORM_ARM_TENANT_ID }}
        run: |
          ./build_and_push.sh