name: Deploy Training

on:
  workflow_dispatch:
  release:
    types: [released]

env:
  DEPLOY_ENV: training

jobs:
  docker-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ACR
        run: docker login ${{ secrets.ACR_REPO_URL }} -u ${{ secrets.ACR_ADMIN_USERNAME }} -p ${{ secrets.ACR_ADMIN_PASWORD }}
      - name: Build and push Docker images
        run: ./build_and_push.sh
  deploy-backend:
    runs-on: ubuntu-latest
    needs: docker-build
    defaults:
      run:
        working-directory: ./backend
    env:
      ARM_CLIENT_ID: ${{ secrets.TERRAFORM_ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.TERRAFORM_ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.TERRAFORM_ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TERRAFORM_ARM_TENANT_ID }}
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.10
      - name: Terraform Init
        working-directory: ${{ github.workspace }}/ops/${{ env.DEPLOY_ENV }}
        run: terraform init
      - name: Azure deploy Api
        working-directory: ${{ github.workspace }}/ops/${{ env.DEPLOY_ENV }}
        run: terraform apply -auto-approve -var="acr_image_tag=${GITHUB_SHA::7}" -target="module.simple_report_api"
      - name: Wait for staging deploy to complete
        working-directory: ${{ github.workspace }}/ops
        timeout-minutes: 10
        run: make wait-for-${{ env.DEPLOY_ENV }}
      - name: Promote staging to production
        working-directory: ${{ github.workspace }}/ops
        run: make promote-${{ env.DEPLOY_ENV }}
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: ./.github/actions/deploy-front-end
        name: Build and deploy front-end application
        with:
          deploy-env: ${{env.DEPLOY_ENV}}
          smarty-streets-key: ${{ secrets.SMARTY_STREETS_KEY }}
          is-training-site: true
