name: Deploy Frontend Azure Resources

on:
  workflow_dispatch:
  push:
    branches:
      - ci_cd
#    paths:
#      - "frontend/**"
#      - ".github/workflows/deployAzureFrontend.yml"

env:
  ACR_ADMIN_USERNAME: ${{ secrets.ACR_ADMIN_USERNAME }}
  ACR_ADMIN_PASWORD: ${{ secrets.ACR_ADMIN_PASWORD }}
  ACR_REPO_URL: ${{ secrets.ACR_REPO_URL }}

defaults:
  run:
    working-directory: ./frontend

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm install
      - name: Build dependencies
        run: npm run build
      - name: install AZ
        run: sudo apt-get install azure-cli
      - name: Build frontend app artifact
        run: npm run deploy-azure-dev