name: Deploy Demo

on:
  workflow_dispatch:
  release:
    types: [released]

env:
  ARM_CLIENT_ID: ${{ secrets.TERRAFORM_ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.TERRAFORM_ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.TERRAFORM_ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.TERRAFORM_ARM_TENANT_ID }}
  ACR_ADMIN_USERNAME: ${{ secrets.ACR_ADMIN_USERNAME }}
  ACR_ADMIN_PASWORD: ${{ secrets.ACR_ADMIN_PASWORD }}
  ACR_REPO_URL: ${{ secrets.ACR_REPO_URL }}
  DEPLOY_ENV: demo

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ACR
        run: docker login ${{ secrets.ACR_REPO_URL }} -u ${{ secrets.ACR_ADMIN_USERNAME }} -p ${{ secrets.ACR_ADMIN_PASWORD }}
      - name: Build and push Docker images
        run: |
          ./build_and_push.sh
      - uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        working-directory: ${{ github.workspace }}/ops/${{ env.DEPLOY_ENV }}
        run: terraform init
      - name: Azure deploy Api
        working-directory: ${{ github.workspace }}/ops/${{ env.DEPLOY_ENV }}
        run: terraform apply -auto-approve -var="acr_image_tag=${GITHUB_SHA::7}" -target="module.simple_report_api.azurerm_app_service.service"
  deploy-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Install dependencies
        run: yarn install
      - name: Build deploy artifact
        env:
          REACT_APP_BASE_URL: https://demo.simplereport.gov
          REACT_APP_BACKEND_URL: https://demo.simplereport.gov/api
          PUBLIC_URL: /app/
        run: yarn run build
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy frontend app
        run: az storage blob upload-batch -s build/ -d '$web' --account-name simplereportdemoapp --destination-path '/app'
      - name: Purge CDN
        run: az cdn endpoint purge --resource-group prime-simple-report-${{ env.DEPLOY_ENV }} --profile-name simple-report-${{ env.DEPLOY_ENV }} --name simple-report-${{ env.DEPLOY_ENV }} --content-paths "/app/*" --no-wait
