name: Deploy Client Application

env:
  DEMO_CF_APP: "simple-report-qa" # the app name if we are deploying 'main'
  SANDBOX_CF_APP: "simple-report-sandbox" # the app name if we are deploying any other branch
  NODE_VERSION: 14
on:
  workflow_dispatch: # run when somebody pushes the button (on whatever branch they choose)
  push:
    branches: # automatically deploy the "sandbox" and "main" branches to their respective envs
      - sandbox
      - main
  schedule:
    - cron: "03 12 * * *" # deploy main every day at 12:03 UTC
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # VERY IMPORTANT: if you run this on any branch other than master, it will
        # deploy to SANDBOX_CF_APP
      - name: Choose deployment environment
        run: |
          if  [[ "$GITHUB_REF" == "refs/heads/main" ]] ; then
            echo We are deploying to the DEMO environment
            app=$DEMO_CF_APP
            title="SimpleReportQA"
          else
            echo We are deploying to the SANDBOX environment
            app=$SANDBOX_CF_APP
            title="** DEV/TEST ** SimpleReport ** DEV/TEST **"
            echo >> $GITHUB_ENV "REACT_APP_ICON=optimus_prime.svg"
          fi
          echo >> $GITHUB_ENV "CF_APPLICATION=$app"
          echo >> $GITHUB_ENV "REACT_APP_TITLE=$title"
      - name: Use Node.js ${{env.NODE_VERSION}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}
      - name: Cache npm local files
        uses: actions/cache@v2
        with:
          path: |
            ./frontend/node_modules
          key: npm-build-${{env.NODE_VERSION}}-${{ hashFiles('frontend/yarn.lock', 'frontend/package.json') }}
      - name: Install Dependencies
        working-directory: ./frontend
        run: yarn
      - name: Application build
        working-directory: ./frontend
        run: yarn build
      - name: Deploy
        uses: usds/cloud-gov-cli@master
        with:
          org: ${{secrets.CLOUD_GOV_ORG}}
          user: ${{secrets.SERVICE_USER}}
          password: ${{secrets.SERVICE_PASSWORD}}
          application: ${{env.CF_APPLICATION}}
          manifest: frontend/manifest.yml
