name: Restage Application

on:
  workflow_dispatch:
    inputs:
      deploy-to:
        description: Which instance should we restage ("qa" or "sandbox" or "qa-api")?
        default: sandbox
jobs:
  restage:
    runs-on: ubuntu-latest
    steps:
      - name: Restage Application
        uses: usds/cloud-gov-cli@master
        with:
          org: ${{secrets.CLOUD_GOV_ORG}}
          user: ${{secrets.SERVICE_USER}}
          password: ${{secrets.SERVICE_PASSWORD}}
          application: simple-report-${{github.event.inputs.deploy-to}}
          command: restage
