# Smoketest/code lint checks for frontend package
name: Smoke Test Client

# Run this on pushes to any branch that change a frontend file or the workflow definition
on:
  push:
    branches: "**"
    paths:
      - "frontend/**"
      - .github/workflows/smoketest.yml

defaults:
  run:
    working-directory: frontend
jobs:
  smoketest:
    strategy:
      matrix:
        node: [14]
        os: [ubuntu-18.04, ubuntu-20.04]
    runs-on: ${{matrix.os}}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node}}
      - name: Cache npm local files
        uses: actions/cache@v2
        with:
          path: |
            ./frontend/node_modules
          key: npm-${{matrix.node}}-${{ hashFiles('frontend/yarn.lock', 'frontend/package.json') }}
      - name: Node setup
        run: yarn
      - name: Test
        run: yarn test
      - name: E2E Test
        run: yarn e2e
  linter:
    strategy:
      matrix:
        node: [14]
        os: [ubuntu-18.04, ubuntu-20.04]
    runs-on: ${{matrix.os}}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node}}
      - name: Cache npm local files
        uses: actions/cache@v2
        with:
          path: |
            ./frontend/node_modules
          key: npm-${{matrix.node}}-${{ hashFiles('frontend/yarn.lock', 'frontend/package.json') }}
      - name: Node setup
        run: yarn
      - name: Lint
        run: yarn lint
  build-test:
    strategy:
      matrix:
        node: [14]
        os: [ubuntu-18.04, ubuntu-20.04]
    runs-on: ${{matrix.os}}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node}}
      - name: Cache npm local files
        uses: actions/cache@v2
        with:
          path: |
            ./frontend/node_modules
          key: npm-${{matrix.node}}-${{ hashFiles('frontend/yarn.lock', 'frontend/package.json') }}
      - name: Install dependencies
        run: yarn
      - name: Build release
        run: yarn build
