name: Terraform Checks

on:
  workflow_dispatch: # because sometimes you just want to force a branch to have tests run
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./ops

jobs:
  check-terraform-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.1
      - name: Terraform fmt
        run: terraform fmt -check -recursive

  check-terraform-validity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.1
      - name: Terraform Init
        run: |
          pushd dev; pushd persistent; terraform init -backend=false; popd; terraform init -backend=false; popd
          pushd test; pushd persistent; terraform init -backend=false; popd; terraform init -backend=false; popd
          pushd demo; pushd persistent; terraform init -backend=false; popd; terraform init -backend=false; popd
          pushd stg; pushd persistent; terraform init -backend=false; popd; terraform init -backend=false; popd
          pushd prod; pushd persistent; terraform init -backend=false; popd; terraform init -backend=false; popd
          pushd pentest; pushd persistent; terraform init -backend=false; popd; terraform init -backend=false; popd
          pushd global; terraform init -backend=false;

      - name: Terraform Validate
        run: |
          pushd dev; pushd persistent; echo $PWD && terraform validate -no-color; popd; echo $PWD && terraform validate -no-color; popd
          pushd test; pushd persistent; echo $PWD && terraform validate -no-color; popd; echo $PWD && terraform validate -no-color; popd
          pushd demo; pushd persistent; echo $PWD && terraform validate -no-color; popd; echo $PWD && terraform validate -no-color; popd
          pushd stg; pushd persistent; echo $PWD && terraform validate -no-color; popd; echo $PWD && terraform validate -no-color; popd
          pushd prod; pushd persistent; echo $PWD && terraform validate -no-color; popd; echo $PWD && terraform validate -no-color; popd
          pushd pentest; pushd persistent; echo $PWD && terraform validate -no-color; popd; echo $PWD && terraform validate -no-color; popd
          pushd global; echo $PWD && terraform validate -no-color;