---
name: Infra Checks

on:
  workflow_dispatch: # because sometimes you just want to force a branch to have tests run
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./ops

env:
  ARM_CLIENT_ID: ${{ secrets.TERRAFORM_ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.TERRAFORM_ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.TERRAFORM_ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.TERRAFORM_ARM_TENANT_ID }}

jobs:
  validation_and_formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1

      - name: Terraform fmt
        run: |
          terraform fmt -check -recursive

      - name: Terraform Init
        run: |
          pushd dev; pushd persistent; echo $PWD && terraform init; popd; echo $PWD && terraform init; popd
          pushd test; pushd persistent; echo $PWD && terraform init; popd; echo $PWD && terraform init; popd
          pushd demo; pushd persistent; echo $PWD && terraform init; popd; echo $PWD && terraform init; popd
          pushd stg; pushd persistent; echo $PWD && terraform init; popd; echo $PWD && terraform init; popd
          pushd prod; pushd persistent; echo $PWD && terraform init; popd; echo $PWD && terraform init; popd
          pushd pentest; pushd persistent; echo $PWD && terraform init; popd; echo $PWD && terraform init; popd
          pushd global; echo $PWD && terraform init;

      - name: Terraform Validate
        run: |
          pushd dev; pushd persistent; echo $PWD && terraform validate -no-color; popd; echo $PWD && terraform validate -no-color; popd
          pushd test; pushd persistent; echo $PWD && terraform validate -no-color; popd; echo $PWD && terraform validate -no-color; popd
          pushd demo; pushd persistent; echo $PWD && terraform validate -no-color; popd; echo $PWD && terraform validate -no-color; popd
          pushd stg; pushd persistent; echo $PWD && terraform validate -no-color; popd; echo $PWD && terraform validate -no-color; popd
          pushd prod; pushd persistent; echo $PWD && terraform validate -no-color; popd; echo $PWD && terraform validate -no-color; popd
          pushd pentest; pushd persistent; echo $PWD && terraform validate -no-color; popd; echo $PWD && terraform validate -no-color; popd
          pushd global; echo $PWD && terraform validate -no-color;